component-definition: ./pkg/testdata/ocm/component-definition.json
plugins:
  ocm:
    policy-dir: ./pkg/testdata/ocm/policies
    policy-results-dir: ./pkg/testdata/ocm/policy-results
    temp-dir: /tmp/ocm
    policy-set-name: "Managed Kubernetes"
    namespace: "c2p"